#!/bin/bash
set -e

## 01: Release and post release
pushd test-fixture
../release 1.0.0 --no-git-commit > /dev/null
popd

git diff --unified=0 > 01-actual.diff
diff 01-actual.diff 01-expected.diff

## 02: Only release
pushd test-fixture
../release 1.0.0 --no-git-commit --only-release > /dev/null
popd

git diff --unified=0 > 02-actual.diff
diff 02-actual.diff 01-expected.diff


git reset --hard HEAD
